version: "3.3"

services:

  #|------------------------------------------
  #| InfluxDB
  #|------------------------------------------
  influxdb:
    image: influxdb:1.4-alpine
    environment:
      INFLUXDB_DB: "PlarkRateTracker"
      INFLUXDB_GRAPHITE_ENABLED: 'true'
      INFLUXDB_ADMIN_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: plark
      INFLUXDB_ADMIN_PASSWORD: plarp
    ports:
      - 8086:8086 # Main
      - 8083:8083 # Admin
      - 2003:2003 # Graphite
    volumes:
      - "/tmp/influxdb2:/var/lib/influxdb"



  #|------------------------------------------
  #| FrontEnd
  #| WEB Application as NodeJS Express
  #|------------------------------------------
  web:
    image: plark/price-tracker:latest
    environment:
      APP_ENV: production
      HOST: 127.0.0.1
      PORT: 80
      SECURE: "true"
      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      CURRENCYCONVERTERAPI_API_KEY: ""
    ports:
      - 80:80
    depends_on:
      - influxdb
