currency:
  currencyconverterapi:
    apiKey: "provider-API-key"

  fiats: [
    GBP, EUR, HKD, CNY, JPY, CHF, AUD, CAD,
    KRW, UAH, RUB, CZK, KZT, TRY, PHP, SEK,
    AED, INR, VND, SEK, TRY, DKK, IDR, THB, SGD, MYR, ZAR,
    CUP, GIP, JMD, MGA, MAD, PKR, SHP, LKR, ETB, CRC
  ]

  coins: [
    BTC,  DASH,  LTC,  ETH,
    ETC,  XRP,   EOS,  NEO,
    ZEC,  IOTA,  XMR,  BCH,
    BTG,  GNT,   ADA,  BNB,
    XLM,  TRX,   BSV,  XTZ,
    ATOM
  ]

  coin_aliases:
    DASH: DSH
    IOTA: IOT